// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function CancelBulkOperation(arg1:number):Promise<void>;

export function CopyObjects(arg1:domain.BulkCopyRequest):Promise<number>;

export function CreateBucket(arg1:number,arg2:string):Promise<void>;

export function CreateFolder(arg1:domain.CreateFolderRequest):Promise<void>;

export function DeleteBucket(arg1:number,arg2:string):Promise<void>;

export function DeleteObjects(arg1:domain.DeleteObjectsRequest):Promise<number>;

export function GetBucketSize(arg1:number,arg2:string,arg3:string):Promise<domain.BucketSizeResult>;

export function GetPresignedURL(arg1:number,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetTextPreview(arg1:number,arg2:string,arg3:string):Promise<domain.TextPreviewResult>;

export function HeadObject(arg1:number,arg2:string,arg3:string):Promise<domain.ObjectMeta>;

export function ListAllKeysUnderPrefix(arg1:number,arg2:string,arg3:string):Promise<Array<string>>;

export function ListBuckets(arg1:number):Promise<Array<domain.Bucket>>;

export function ListObjects(arg1:domain.ListObjectsRequest):Promise<domain.ListObjectsResponse>;

export function MoveObjects(arg1:domain.BulkMoveRequest):Promise<number>;

export function RenameObject(arg1:domain.RenameObjectRequest):Promise<void>;

export function SearchObjects(arg1:domain.SearchObjectsRequest):Promise<domain.SearchObjectsResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateMetadata(arg1:domain.UpdateMetadataRequest):Promise<void>;
