// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPresignedURL(arg1, arg2, arg3, arg4) {
  return window['go']['filemanager']['FileManagerService']['GetPresignedURL'](arg1, arg2, arg3, arg4);
}

export function GetTextPreview(arg1, arg2, arg3) {
  return window['go']['filemanager']['FileManagerService']['GetTextPreview'](arg1, arg2, arg3);
}

export function HeadObject(arg1, arg2, arg3) {
  return window['go']['filemanager']['FileManagerService']['HeadObject'](arg1, arg2, arg3);
}

export function ListBuckets(arg1) {
  return window['go']['filemanager']['FileManagerService']['ListBuckets'](arg1);
}

export function ListObjects(arg1) {
  return window['go']['filemanager']['FileManagerService']['ListObjects'](arg1);
}
