// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBulkOperation(arg1) {
  return window['go']['filemanager']['FileManagerService']['CancelBulkOperation'](arg1);
}

export function CopyObjects(arg1) {
  return window['go']['filemanager']['FileManagerService']['CopyObjects'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['filemanager']['FileManagerService']['CreateFolder'](arg1);
}

export function DeleteObjects(arg1) {
  return window['go']['filemanager']['FileManagerService']['DeleteObjects'](arg1);
}

export function GetPresignedURL(arg1, arg2, arg3, arg4) {
  return window['go']['filemanager']['FileManagerService']['GetPresignedURL'](arg1, arg2, arg3, arg4);
}

export function GetTextPreview(arg1, arg2, arg3) {
  return window['go']['filemanager']['FileManagerService']['GetTextPreview'](arg1, arg2, arg3);
}

export function HeadObject(arg1, arg2, arg3) {
  return window['go']['filemanager']['FileManagerService']['HeadObject'](arg1, arg2, arg3);
}

export function ListBuckets(arg1) {
  return window['go']['filemanager']['FileManagerService']['ListBuckets'](arg1);
}

export function ListObjects(arg1) {
  return window['go']['filemanager']['FileManagerService']['ListObjects'](arg1);
}

export function MoveObjects(arg1) {
  return window['go']['filemanager']['FileManagerService']['MoveObjects'](arg1);
}

export function RenameObject(arg1) {
  return window['go']['filemanager']['FileManagerService']['RenameObject'](arg1);
}

export function SetContext(arg1) {
  return window['go']['filemanager']['FileManagerService']['SetContext'](arg1);
}

export function UpdateMetadata(arg1) {
  return window['go']['filemanager']['FileManagerService']['UpdateMetadata'](arg1);
}
