// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetPresignedURL(arg1:number,arg2:string,arg3:string,arg4:number):Promise<string>;

export function GetTextPreview(arg1:number,arg2:string,arg3:string):Promise<domain.TextPreviewResult>;

export function HeadObject(arg1:number,arg2:string,arg3:string):Promise<domain.ObjectMeta>;

export function ListBuckets(arg1:number):Promise<Array<domain.Bucket>>;

export function ListObjects(arg1:domain.ListObjectsRequest):Promise<domain.ListObjectsResponse>;
