// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2, arg3) {
  return window['go']['favorites']['FavoritesService']['AddFavorite'](arg1, arg2, arg3);
}

export function GetFavorites() {
  return window['go']['favorites']['FavoritesService']['GetFavorites']();
}

export function RemoveFavorite(arg1) {
  return window['go']['favorites']['FavoritesService']['RemoveFavorite'](arg1);
}
