// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AddFavorite(arg1:number,arg2:string,arg3:string):Promise<domain.Favorite>;

export function GetFavorites():Promise<Array<domain.Favorite>>;

export function RemoveFavorite(arg1:number):Promise<void>;
