// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoResumeIfEnabled(arg1, arg2) {
  return window['go']['transfer']['TransferService']['AutoResumeIfEnabled'](arg1, arg2);
}

export function CancelTask(arg1) {
  return window['go']['transfer']['TransferService']['CancelTask'](arg1);
}

export function ClearHistory() {
  return window['go']['transfer']['TransferService']['ClearHistory']();
}

export function GetHistory(arg1) {
  return window['go']['transfer']['TransferService']['GetHistory'](arg1);
}

export function GetQueue() {
  return window['go']['transfer']['TransferService']['GetQueue']();
}

export function PauseTask(arg1) {
  return window['go']['transfer']['TransferService']['PauseTask'](arg1);
}

export function PickDownloadDestination(arg1) {
  return window['go']['transfer']['TransferService']['PickDownloadDestination'](arg1);
}

export function PickDownloadDirectory() {
  return window['go']['transfer']['TransferService']['PickDownloadDirectory']();
}

export function PickUploadDirectory() {
  return window['go']['transfer']['TransferService']['PickUploadDirectory']();
}

export function PickUploadFiles() {
  return window['go']['transfer']['TransferService']['PickUploadFiles']();
}

export function QueueDownload(arg1) {
  return window['go']['transfer']['TransferService']['QueueDownload'](arg1);
}

export function QueueDownloadPrefix(arg1, arg2, arg3, arg4) {
  return window['go']['transfer']['TransferService']['QueueDownloadPrefix'](arg1, arg2, arg3, arg4);
}

export function QueueUpload(arg1) {
  return window['go']['transfer']['TransferService']['QueueUpload'](arg1);
}

export function QueueUploadPaths(arg1, arg2, arg3, arg4) {
  return window['go']['transfer']['TransferService']['QueueUploadPaths'](arg1, arg2, arg3, arg4);
}

export function RecoverOrphanedTasks() {
  return window['go']['transfer']['TransferService']['RecoverOrphanedTasks']();
}

export function ReorderTask(arg1, arg2) {
  return window['go']['transfer']['TransferService']['ReorderTask'](arg1, arg2);
}

export function ResumeTask(arg1) {
  return window['go']['transfer']['TransferService']['ResumeTask'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['transfer']['TransferService']['RetryTask'](arg1);
}

export function SetBandwidthLimits(arg1, arg2) {
  return window['go']['transfer']['TransferService']['SetBandwidthLimits'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['transfer']['TransferService']['SetContext'](arg1);
}

export function SetMaxConcurrentTasks(arg1) {
  return window['go']['transfer']['TransferService']['SetMaxConcurrentTasks'](arg1);
}

export function SetPartSizeOverrideMB(arg1) {
  return window['go']['transfer']['TransferService']['SetPartSizeOverrideMB'](arg1);
}
