// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function AutoResumeIfEnabled(arg1:Array<number>,arg2:boolean):Promise<void>;

export function CancelTask(arg1:number):Promise<void>;

export function CancelTasksForProfile(arg1:number):Promise<number>;

export function ClearHistory():Promise<void>;

export function GetHistory(arg1:number):Promise<Array<domain.TransferHistoryEntry>>;

export function GetQueue():Promise<Array<domain.TransferTask>>;

export function PauseTask(arg1:number):Promise<void>;

export function PickDownloadDestination(arg1:string):Promise<string>;

export function PickDownloadDirectory():Promise<string>;

export function PickUploadDirectory():Promise<string>;

export function PickUploadFiles():Promise<Array<string>>;

export function QueueDownload(arg1:domain.DownloadRequest):Promise<number>;

export function QueueDownloadPrefix(arg1:number,arg2:string,arg3:string,arg4:string):Promise<Array<number>>;

export function QueueDownloadPrefixZip(arg1:number,arg2:string,arg3:string,arg4:string):Promise<number>;

export function QueueUpload(arg1:domain.UploadRequest):Promise<number>;

export function QueueUploadPaths(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<number>>;

export function RecoverOrphanedTasks():Promise<Array<number>>;

export function ReorderTask(arg1:number,arg2:number):Promise<void>;

export function ResumeTask(arg1:number):Promise<void>;

export function RetryTask(arg1:number):Promise<number>;

export function SetBandwidthLimits(arg1:number,arg2:number):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetMaxConcurrentTasks(arg1:number):Promise<void>;

export function SetPartSizeOverrideMB(arg1:number):Promise<void>;
