// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySettings(arg1) {
  return window['go']['appsettings']['SettingsService']['ApplySettings'](arg1);
}

export function GetSettings() {
  return window['go']['appsettings']['SettingsService']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['appsettings']['SettingsService']['SaveSettings'](arg1);
}
