// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmClose():Promise<void>;

export function GetAppVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;
