// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DeleteProfile(arg1:number):Promise<void>;

export function GetProfile(arg1:number):Promise<domain.Profile>;

export function GetProfiles():Promise<Array<domain.ProfileDTO>>;

export function SaveProfile(arg1:domain.Profile):Promise<domain.Profile>;

export function TestConnection(arg1:domain.Profile):Promise<domain.ConnectionTestResult>;
