// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['connection']['ConnectionService']['DeleteProfile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['connection']['ConnectionService']['GetProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['connection']['ConnectionService']['GetProfiles']();
}

export function SaveProfile(arg1) {
  return window['go']['connection']['ConnectionService']['SaveProfile'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['connection']['ConnectionService']['TestConnection'](arg1);
}
