// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {connection} from '../models';
import {context} from '../models';

export function DeleteProfile(arg1:number):Promise<void>;

export function ExportProfiles():Promise<void>;

export function GetProfile(arg1:number):Promise<domain.Profile>;

export function GetProfiles():Promise<Array<domain.ProfileDTO>>;

export function ImportProfiles():Promise<connection.ImportResult>;

export function SaveProfile(arg1:domain.Profile):Promise<domain.Profile>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TestConnection(arg1:domain.Profile):Promise<domain.ConnectionTestResult>;
